name: deploy
on:
  workflow_run:
    workflows: ["undeploy"]      
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            cd /home/ubuntu/github-actions/
            echo "Pulling latest code..."
            git pull origin main
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements.txt
            echo "Running app..."
            nohup python3 app.py > output.log 2>&1 &
            