name: deploy testing
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     # Deploy on remote server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/pborde/Projects/py3-telegram-bot
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python3 -m bot