name: deploy testing
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Current directory: $(pwd)"
            cd /home/pborde/test/
            echo "Pulling latest code..."
            git pull origin main
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements.txt
            echo "Running app..."
            python3 -m app