name: undeploy
on:
  push:
    branches:
      - main

jobs:
  call-host-workflow:
    uses: ./.github/workflows/get-ec2-host.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.call-host-workflow.outputs.host }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            cd /home/ubuntu/github-actions/
            echo "Killing any existing app.py processes..."
            pkill -f '[p]ython3 app.py'
            